<a href="https://colab.research.google.com/github/InnCreator/100DaysOfMlCode/blob/master/Numpy_Intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
# A list of lists in converted to a 2-dimensional array
import numpy as np

original_list = [[1,2,3],[3,4,5],[6,7,8]]
two_dimensional_array = np.array(original_list)
two_dimensional_array


array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
np.arange(0, 20, 2)


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [9]:
# An array of 5 numbers, linearly spaced between 0 and 1
np.linspace(0, 1, 5)


array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [10]:
np.random.seed(0)
x1 = np.random.randint(10, size=6)  
# 1-dimensional array
print("Number of dimensions: ", x1.ndim)
print("Shape: ", x1.shape)
print("Size: ", x1.size)
print("Type: ", x1.dtype)

Number of dimensions:  1
Shape:  (6,)
Size:  6
Type:  int64


In [11]:
def calculate_inverse(values):    
    output = np.empty(len(values))    
    for i in range(len(values)):        
        output[i] = 1.0 / values[i]    
    return output       

values = np.random.randint(1, 10, size=5)
print(calculate_inverse(values))

large_array = np.random.randint(1, 100, size=1000000)

# This is a Jupyter notebook tool to measure the execution
# time of an instruction
%timeit calculate_inverse(large_array)

[0.25       0.16666667 0.33333333 0.2        0.125     ]
1 loop, best of 3: 2.58 s per loop


In [12]:
# Simple mathematics first
x = np.arange(4)
print("x     =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
# Divide and round
print("x // 2 =", x // 2)  

x     = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]
