# Numpy

fundamental package for scientific computing in Python for multidimensional arrays, high level mathematical functions and pseudorandom number generators.

In [4]:
import numpy as np

x = np.array([[1,2,3],[4,5,6]])
print("x:\n{}".format(x))

x:
[[1 2 3]
 [4 5 6]]


# Scipy

Collections of functions fo scientific computing in python for advanced linear algebra, stats distributions, math function optimization, signal processing and special math functions.

In [5]:
from scipy import sparse

#a 2D Numpy array with a diagonal of ones and zeroes everywhere else

eye = np.eye(4)
print("Numpy array:\n", eye)

Numpy array:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [6]:
#converting numpy array to a scipy sparse matrix in CSR format
#only nonzero elements are stored

sparse_matrix = sparse.csr_matrix(eye)
print('\nSciPy sparse CSR matrix:\n', sparse_matrix)


SciPy sparse CSR matrix:
   (0, 0)	1.0
  (1, 1)	1.0
  (2, 2)	1.0
  (3, 3)	1.0


In [12]:
data = np.ones(4)
row_indices = np.arange(4)
col_indices = np.arange(4)
eye_coo = sparse.coo_matrix(data, (row_indices, col_indices))
print("COO representation:\n", eye_coo)

COO representation:
   (0, 0)	1.0
  (0, 1)	1.0
  (0, 2)	1.0
  (0, 3)	1.0
